// ملف الترجمة - translation.js
const translations = {
    en: {
        // Header
        web7_logo_text: "WEB 7",
        nav_home: "Home",
        nav_services: "Services",
        nav_portfolio: "Portfolio",
        nav_process: "Process",
        nav_pricing: "Pricing",
        nav_contact: "Contact",
        lang_arabic: "Arabic",
        lang_english: "English",
        lang_french: "French",

        // Hero Section
        hero_badge: "Certified Web Developer",
        hero_title: "Turn Your Ideas into Professional Websites & Pages",
        hero_subtitle: "I build websites and web pages that help grow your business and increase your profits, with modern designs and a smooth user experience.",
        stat_completed_projects_count: "+36",
        stat_completed_projects: "Completed Projects",
        stat_happy_clients_count: "+36",
        stat_happy_clients: "Happy Clients",
        stat_improvements_count: "+15",
        stat_improvements: "Edits & Improvements",
        cta_start_project: "Start Your Project Now",
        cta_view_work: "View My Work",

        // Trust Section
        trust_custom_design_title: "Custom Design",
        trust_custom_design_desc: "100% yours",
        trust_support_title: "24/7 Support",
        trust_support_desc: "All week long",
        trust_fast_delivery_title: "Fast Delivery",
        trust_fast_delivery_desc: "Within 7-14 days",
        trust_clean_code_title: "Clean & Secure Code",
        trust_clean_code_desc: "With latest technologies",

        // Services Section
        services_section_title: "Services",
        services_section_heading: "What Do I Offer?",
        services_section_subtitle: "Integrated solutions that fit your needs and help you achieve your digital goals",
        service_company_websites_title: "Company Websites",
        service_company_websites_desc: "Professional websites that reflect your company's identity and present your services distinctively",
        service_feature_custom_design: "Custom Design",
        service_feature_responsive: "Responsive on all devices",
        service_feature_seo: "SEO Optimization",
        service_landing_pages_title: "Landing Pages",
        service_landing_pages_desc: "Professional marketing pages that increase conversion rates",
        service_feature_attractive_design: "Attractive Design",
        service_feature_high_speed: "High Speed",
        service_feature_responsive_all: "Responsive on all devices",
        service_product_landing_pages_title: "Product Landing Pages",
        service_product_landing_pages_desc: "Custom landing pages for your products designed to increase sales and convert visitors into customers, with full focus on persuasion and ease of purchase.",
        service_feature_sales_oriented: "Sales-oriented design",
        service_feature_high_load_speed: "High loading speed to reduce bounce rate",
        service_feature_sales_optimized: "Optimized to increase sales and achieve real results",
        service_brand_websites_title: "Professional Websites for Brands & Services",
        service_brand_websites_desc: "Professional websites that reflect your brand's strength, suitable for restaurants, hotels, clinics, and companies, with a distinctive user experience that builds trust and attracts customers.",
        service_feature_brand_identity: "Design that reflects brand identity",
        service_feature_interactive_services: "Booking and interactive services (Restaurants / Clinics / Hotels)",
        service_feature_search_visibility: "Improved search engine visibility",
        service_figma_conversion_title: "Convert Figma Design to Real Website",
        service_figma_conversion_desc: "I convert your design from Figma to a professional, fast, responsive website that works on all devices with clean and organized code.",
        service_feature_accurate_conversion: "Accurate conversion of the design as in Figma",
        service_feature_clean_code: "Clean code that's easy to modify in the future",
        service_feature_responsive_mobile_desktop: "Website responsive on mobile and desktop",
        service_seo_title: "SEO Optimization",
        service_seo_desc: "Advanced search results to increase visitors",
        service_feature_keyword_analysis: "Keyword Analysis",
        service_feature_speed_optimization: "Speed Optimization",
        service_feature_clean_urls: "Clean URLs",

        // Portfolio Section
        portfolio_section_title: "Portfolio",
        portfolio_section_heading: "Previous Projects",
        portfolio_section_subtitle: "A collection of projects I have executed for clients in various fields",
        portfolio_real_estate_title: "Real Estate Company Website",
        portfolio_dentist_title: "Landing Page for Dental Clinic",
        portfolio_hotel_title: "Hotel Website",
        trestt: "Sell Your Property Fast and Professionally with a Website That Shows It at Its Best",
        trrestp: "A website specially designed for property owners to showcase their properties attractively, clearly display prices and features, attract clients, and increase sales opportunities.",
        trdtt: "Attract More Dental Patients with an Easy and Professional Booking Page",
        trdd: "A landing page specially designed for your clinic, professionally showcasing your services and allowing patients to book appointments easily, increasing bookings and simplifying your management.",
        trhtt: "Boost Your Hotel Bookings with a Fast, Professional Website That Attracts Guests",
        trhtd: "A website designed for hotels to increase bookings, fast, responsive on all devices, professionally showcasing your services with a booking system that lets guests reserve instantly.",


        // Why Us Section
        why_us_section_title: "Why WEB 7?",
        why_us_section_heading: "Reasons to Choose Me",
        why_us_section_subtitle: "Experience, quality, and professionalism in every project",
        why_real_results_title: "Real Results",
        why_real_results_desc: "Websites designed to increase customers and sales",
        why_performance_title: "High Performance & Speed",
        why_performance_desc: "Fast websites optimized for perfect user experience",
        why_on_time_title: "On-Time Delivery",
        why_on_time_desc: "Always committed to deadlines",
        why_free_support_title: "Free Support",
        why_free_support_desc: "One week after delivery",

        // Testimonials
        testimonial_1_text: "I've worked with several developers, but WEB 7 was the best in every sense. He understood my needs precisely and executed the project with high professionalism, committed to deadlines and was in constant communication with me throughout the work period.",
        testimonial_1_name: "Ahmed Ali",
        testimonial_1_role: "Successful Product Landing Page",
        testimonial_2_text: "Honestly, I didn't expect the website to make such a difference. I just wanted an online presence. But after Mohamed worked on it, I noticed more people visiting, inquiring, and even coming to the restaurant. A huge difference compared to before. I truly felt my service reached people.",
        testimonial_2_name: "Abdulrahman",
        testimonial_2_role: "Restaurant Website",
        testimonial_3_text: "Honestly, I didn't expect a simple page to make such a difference. I thought it was just a secondary thing. But after working with WEB 7, I noticed more people contacting me and booking appointments, and inquiries increased significantly. A huge difference compared to how things were before.",
        testimonial_3_name: "Khaled",
        testimonial_3_role: "Landing Page for Dental Clinic",
        testimonial_4_text: "I've worked with several developers, but WEB 7 was the best in every sense. He understood my needs precisely and executed the project with high professionalism, committed to deadlines and was in constant communication with me throughout the work period.",
        testimonial_4_name: "Ahmed Ali",
        testimonial_4_role: "Successful Product Landing Page",
        testimonial_5_text: "Honestly, I didn't expect the website to make such a difference. I just wanted an online presence. But after Mohamed worked on it, I noticed more people visiting, inquiring, and even coming to the restaurant. A huge difference compared to before. I truly felt my service reached people.",
        testimonial_5_name: "Abdulrahman",
        testimonial_5_role: "Restaurant Website",
        testimonial_6_text: "Honestly, I didn't expect a simple page to make such a difference. I thought it was just a secondary thing. But after working with WEB 7, I noticed more people contacting me and booking appointments, and inquiries increased significantly. A huge difference compared to how things were before.",
        testimonial_6_name: "Khaled",
        testimonial_6_role: "Landing Page for Dental Clinic",

        // Process Section
        process_section_title: "Work Process",
        process_section_heading: "How Do I Work With You?",
        process_section_subtitle: "Clear and organized steps to ensure the best result",
        process_step1_title: "Free Consultation",
        process_step1_desc: "We talk about your idea, goals, and project requirements",
        process_step2_title: "Design & Planning",
        process_step2_desc: "I provide you with a prototype of the website for approval",
        process_step3_title: "Development & Coding",
        process_step3_desc: "Building the website with the latest technologies with periodic reviews",
        process_step4_title: "Delivery & Support",
        process_step4_desc: "We launch the website with guaranteed technical support for one week",

        // Pricing Section
        pricing_section_title: "Packages & Prices",
        pricing_section_heading: "Choose the Right Package",
        pricing_section_subtitle: "Competitive prices with guaranteed quality and professionalism",
        pricing_landing_pages_type: "Landing Pages",
        pricing_basic_landing_title: "Basic Package",
        pricing_basic_landing_feature_1: "Single Page",
        pricing_basic_landing_feature_2: "4 Sections",
        pricing_basic_landing_feature_3: "Responsive Design",
        pricing_basic_landing_feature_4: "Contact Form",
        pricing_basic_landing_feature_5: "Social Media Icons",
        pricing_professional_landing_title: "Professional Package",
        pricing_professional_landing_feature_1: "Single Page",
        pricing_professional_landing_feature_2: "9 Sections",
        pricing_professional_landing_feature_3: "Custom Design",
        pricing_professional_landing_feature_4: "Responsive on all devices",
        pricing_professional_landing_feature_5: "Contact Form",
        pricing_professional_landing_feature_6: "Social Media Icons",
        pricing_professional_landing_feature_7: "SEO Optimization",
        pricing_premium_landing_title: "Premium Package",
        pricing_premium_landing_feature_1: "3 Pages",
        pricing_premium_landing_feature_2: "Professional & Custom Design",
        pricing_premium_landing_feature_3: "Responsive on all devices",
        pricing_premium_landing_feature_4: "Contact Form",
        pricing_premium_landing_feature_5: "Social Media Icons",
        pricing_premium_landing_feature_6: "Strong SEO Optimization",
        pricing_premium_landing_feature_7: "Free support for two weeks after delivery",
        pricing_most_popular_badge: "Most Popular",
        pricing_order_button: "Order Now",
        pricing_full_websites_type: "Websites Prices",
        pricing_basic_full_title: "Basic Package",
        pricing_basic_full_feature_1: "5 Main Pages",
        pricing_basic_full_feature_2: "Sleek Design",
        pricing_basic_full_feature_3: "Compatible with all devices",
        pricing_basic_full_feature_4: "Ready Contact Page",
        pricing_basic_full_feature_5: "Integrated Social Media Icons",
        pricing_professional_full_title: "Professional Package",
        pricing_professional_full_feature_1: "8–10 Complete Pages",
        pricing_professional_full_feature_2: "Custom design reflecting brand identity",
        pricing_professional_full_feature_3: "Responsive on all devices",
        pricing_professional_full_feature_4: "Integrated Contact Form",
        pricing_professional_full_feature_5: "Basic SEO Optimization",
        pricing_professional_full_feature_6: "Social icons, image gallery, videos",
        pricing_professional_full_feature_7: "Enhanced User Experience",
        pricing_premium_full_title: "Premium Package",
        pricing_premium_full_feature_1: "12–15 pages or more based on request",
        pricing_premium_full_feature_2: "Professional & Fully Custom Design",
        pricing_premium_full_feature_3: "Complete Visual Identity",
        pricing_premium_full_feature_4: "Excellent user experience on all devices",
        pricing_premium_full_feature_5: "Multiple forms, multiple communication portals",
        pricing_premium_full_feature_6: "Full SEO Optimization + High Website Speed",
        pricing_premium_full_feature_7: "Free support for two weeks after delivery",

        // Contact Section
        contact_section_title: "Contact Me",
        contact_section_heading: "Start Your Project Now",
        contact_section_subtitle: "Fill out the form and I will contact you within 24 hours",
        contact_form_title: "Let's Create Something Amazing Together",
        contact_form_subtitle: "Tell me about your project and I will provide you with the best solutions",
        contact_full_name: "Full Name *",
        contact_email: "Email *",
        contact_project_details: "Project Details *",
        service_type_placeholder: "Service Type",
        service_type_full_website: "Full Website",
        service_type_landing_page: "Landing Page",
        service_required_placeholder: "Required Service",
        service_required_company: "Company Website",
        service_required_product_landing: "Product Landing Page",
        service_required_brand: "Website for Your Brand",
        service_required_other: "Other",
        package_type_placeholder: "Package Type",
        package_basic: "Basic Package",
        package_professional: "Professional Package",
        package_premium: "Premium Package",
        contact_submit_button: "Send Request",

        // FAQ Section
        faq_section_title: "Frequently Asked Questions",
        faq_section_heading: "Answers to Your Questions",
        faq_section_subtitle: "I answer the most common questions to help you make a decision",
        faq_q1: "How long does it take to build a complete website?",
        faq_a1: "It depends on the project size. Simple websites take two weeks, e-commerce sites 3-4 weeks.",
        faq_q2: "Do you provide hosting and domain services?",
        faq_a2: "No, but if you are a beginner and don't know how to launch your website, I help you launch it.",
        faq_q3: "What happens after website delivery?",
        faq_a3: "You purchase hosting and launch your website on it.",
        faq_q4: "Can you modify an existing website?",
        faq_a4: "Absolutely, I provide development and improvement services for existing websites.",

        // Footer
        footer_logo: "WEB 7",
        footer_about_text: "Professional web developer with 7 years of experience. I help companies and individuals build a strong digital presence that achieves their goals.",
        footer_quick_links_title: "Quick Links",
        footer_link_home: "Home",
        footer_link_services: "Services",
        footer_link_portfolio: "Portfolio",
        footer_link_contact: "Contact",
        footer_services_title: "Services",
        footer_service_company: "Company Websites",
        footer_service_landing_pages: "Landing Pages",
        footer_service_brand: "Brand Websites",
        footer_service_product_landing: "Product Landing Pages",
        footer_copyright: "All Rights Reserved"
    },
    ar: {
        // Header
        web7_logo_text: "WEB 7",
        nav_home: "الرئيسية",
        nav_services: "الخدمات",
        nav_portfolio: "أعمالي",
        nav_process: "طريقة العمل",
        nav_pricing: "الباقات",
        nav_contact: "اتصل بي",
        lang_arabic: "عربي",
        lang_english: "EN",
        lang_french: "FR",

        // Hero Section
        hero_badge: "مطور ويب معتمد",
        hero_title: "أحول أفكارك الى مواقع وصفحات احترافية",
        hero_subtitle: "أبني مواقع و صفحات ويب تساهم في نمو أعمالك و زيادة أرباحك, بتصاميم عصرية و تجربة مستخدم سلسة",
        stat_completed_projects_count: "36+",
        stat_completed_projects: "مشروع مكتمل",
        stat_happy_clients_count: "36+",
        stat_happy_clients: "عميل سعيد",
        stat_improvements_count: "15+",
        stat_improvements: "تعديل و تحسين",
        cta_start_project: "ابدأ مشروعك الان",
        cta_view_work: "شاهد أعمالي",

        // Trust Section
        trust_custom_design_title: "تصميم مخصص",
        trust_custom_design_desc: "100% لك",
        trust_support_title: "دعم فني 24/7",
        trust_support_desc: "طوال أيام الأسبوع",
        trust_fast_delivery_title: "تسليم سريع",
        trust_fast_delivery_desc: "خلال 7-14 يوم",
        trust_clean_code_title: "كود نظيف وآمن",
        trust_clean_code_desc: "بأحدث التقنيات",

        // Services Section
        services_section_title: "الخدمات",
        services_section_heading: "ماذا أقدم لك؟",
        services_section_subtitle: "حلول متكاملة تناسب احتياجاتك وتساعدك في تحقيق أهدافك الرقمية",
        service_company_websites_title: "مواقع شركات",
        service_company_websites_desc: "مواقع احترافية تعكس هوية شركتك وتقدم خدماتك بشكل مميز",
        service_feature_custom_design: "تصميم مخصص",
        service_feature_responsive: "متجاوب مع كل الأجهزة",
        service_feature_seo: "تحسين محركات البحث",
        service_landing_pages_title: "صفحات هبوط",
        service_landing_pages_desc: "صفحات تسويقية احترافية تزيد من معدلات التحويل",
        service_feature_attractive_design: "تصميم جذاب",
        service_feature_high_speed: "سرعة عالية",
        service_feature_responsive_all: "متجاوبة مع كل الأجهزة",
        service_product_landing_pages_title: "صفحات هبوط للمنتجات",
        service_product_landing_pages_desc: "صفحات هبوط مخصصة لمنتجاتك مصممة لزيادة المبيعات وتحويل الزوار إلى عملاء، مع تركيز كامل على الإقناع وسهولة الشراء.",
        service_feature_sales_oriented: "تصميم موجه للبيع",
        service_feature_high_load_speed: "سرعة تحميل عالية لخفض نسبة الخروج",
        service_feature_sales_optimized: "مهيأة لزيادة المبيعات وتحقيق نتائج حقيقية",
        service_brand_websites_title: "مواقع احترافية للبراندات والخدمات",
        service_brand_websites_desc: "مواقع احترافية تعكس قوة علامتك التجارية وتناسب المطاعم، الفنادق، العيادات والشركات، مع تجربة مستخدم مميزة تبني الثقة وتجذب العملاء.",
        service_feature_brand_identity: "تصميم يعكس هوية البراند",
        service_feature_interactive_services: "حجز وخدمات تفاعلية (مطاعم / عيادات / فنادق)",
        service_feature_search_visibility: "تحسين الظهور في محركات البحث",
        service_figma_conversion_title: "تحويل تصميم Figma إلى موقع حقيقي",
        service_figma_conversion_desc: "أقوم بتحويل تصميمك من Figma إلى موقع ويب احترافي سريع ومتجاوب يعمل على جميع الأجهزة مع كود نظيف ومنظم.",
        service_feature_accurate_conversion: "تحويل دقيق للتصميم كما هو في Figma",
        service_feature_clean_code: "كود نظيف وسهل التعديل مستقبلاً",
        service_feature_responsive_mobile_desktop: "موقع متجاوب مع الجوال والكمبيوتر",
        service_seo_title: "تحسين محركات البحث",
        service_seo_desc: "ظهور متقدم في نتائج البحث لزيادة الزوار",
        service_feature_keyword_analysis: "تحليل الكلمات",
        service_feature_speed_optimization: "تحسين السرعة",
        service_feature_clean_urls: "روابط نظيفة",

        // Portfolio Section
        portfolio_section_title: "أعمالي",
        portfolio_section_heading: "نماذج مشاريع سابقة",
        portfolio_section_subtitle: "مجموعة من المشاريع التي قمت بتنفيذها لعملاء في مجالات متنوعة",
        portfolio_real_estate_title: "موقع لشركة عقارية",
        portfolio_dentist_title: "صفحة هبوط لعيادة أسنان",
        portfolio_hotel_title: "موقع لفندق",
        trestt: "بيع عقارك بسرعة وباحترافية مع موقع يظهره بأفضل صورة",
        trrestp: "موقع مصمم خصيصًا لأصحاب العقارات لعرض العقارات بشكل جذاب، توضيح الأسعار والمواصفات بدقة، لجذب العملاء وزيادة فرص البيع.",
        trdtt: "اجذب المزيد من مرضى الأسنان مع صفحة حجز سهلة واحترافية",
        trdd: "صفحة هبوط مصممة خصيصًا لعيادتك، تعرض خدماتك بشكل احترافي وتتيح للمرضى حجز مواعيدهم بسهولة، مما يزيد الطلبات ويجعل إدارتك أسهل.",
        trhtt: "زد حجوزات فندقك مع موقع سريع واحترافي يجذب الضيوف",
        trhtd: "موقع مصمم للفنادق يرفع حجوزاتك، سريع، متجاوب مع كل الأجهزة، ويعرض خدماتك بشكل احترافي مع نظام حجز يسهل على الضيوف الحجز فورًا.",

        // Why Us Section
        why_us_section_title: "لماذا WEB 7 ؟",
        why_us_section_heading: "أسباب تدفعك لاختياري",
        why_us_section_subtitle: "خبرة وجودة واحترافية في كل مشروع",
        why_real_results_title: "نتائج حقيقية",
        why_real_results_desc: "مواقع مصممة لزيادة العملاء والمبيعات",
        why_performance_title: "أداء وسرعة عالية",
        why_performance_desc: "مواقع سريعة ومحسّنة لتجربة مستخدم مثالية",
        why_on_time_title: "تسليم في الموعد",
        why_on_time_desc: "التزام بالمواعيد دائما",
        why_free_support_title: "دعم مجاني",
        why_free_support_desc: "مدة أسبوع بعد التسليم",

        // Testimonials
        testimonial_1_text: "عملت مع عدة مطورين لكن WEB 7 كان الأفضل بكل معنى الكلمة. فهم احتياجاتي بدقة ونفذ المشروع باحترافية عالية، والتزم بالمواعيد وكان متواصلاً معي طول فترة العمل.",
        testimonial_1_name: "أحمد علي",
        testimonial_1_role: "صفحة هبوط ناجحة لمنتج",
        testimonial_2_text: "بصراحة ما كنت متوقع يفرق معي الموقع لهدرجة، كنت حاطه بس ليكون عندي حضور على الإنترنت وخلاص. لكن بعد ما اشتغل عليه محمد، بديت نلاحظ الناس تدخل أكثر وتسأل وحتى يجو للمطعم. فرق كبير مقارنة بكيف كان قبل، حسيت فعلاً أنه خدمتي وصلت للناس.",
        testimonial_2_name: "عبد الرحمان",
        testimonial_2_role: "موقع مطعم",
        testimonial_3_text: "بصراحة ما كنت متوقع صفحة بسيطة تفرق معي بهذا الشكل، كنت نحسبها حاجة ثانوية فقط. لكن بعد ما اشتغلت مع WEB 7، بديت نلاحظ عدد أكبر من الناس يتواصلوا معي ويحجزوا، وحتى الاستفسارات زادت بشكل واضح. فرق كبير مقارنة بكيف كان الوضع قبل.",
        testimonial_3_name: "خالد",
        testimonial_3_role: "صفحة هبوط لعيادة أسنان",
        testimonial_4_text: "عملت مع عدة مطورين لكن WEB 7 كان الأفضل بكل معنى الكلمة. فهم احتياجاتي بدقة ونفذ المشروع باحترافية عالية، والتزم بالمواعيد وكان متواصلاً معي طول فترة العمل.",
        testimonial_4_name: "أحمد علي",
        testimonial_4_role: "صفحة هبوط ناجحة لمنتج",
        testimonial_5_text: "بصراحة ما كنت متوقع يفرق معي الموقع لهدرجة، كنت حاطه بس ليكون عندي حضور على الإنترنت وخلاص. لكن بعد ما اشتغل عليه محمد، بديت نلاحظ الناس تدخل أكثر وتسأل وحتى يجو للمطعم. فرق كبير مقارنة بكيف كان قبل، حسيت فعلاً أنه خدمتي وصلت للناس.",
        testimonial_5_name: "عبد الرحمان",
        testimonial_5_role: "موقع مطعم",
        testimonial_6_text: "بصراحة ما كنت متوقع صفحة بسيطة تفرق معي بهذا الشكل، كنت نحسبها حاجة ثانوية فقط. لكن بعد ما اشتغلت مع WEB 7، بديت نلاحظ عدد أكبر من الناس يتواصلوا معي ويحجزوا، وحتى الاستفسارات زادت بشكل واضح. فرق كبير مقارنة بكيف كان الوضع قبل.",
        testimonial_6_name: "خالد",
        testimonial_6_role: "صفحة هبوط لعيادة أسنان",

        // Process Section
        process_section_title: "طريقة العمل",
        process_section_heading: "كيف أعمل معك؟",
        process_section_subtitle: "خطوات واضحة و منظمة لضمان أفضل نتيجة",
        process_step1_title: "استشارة مجانية",
        process_step1_desc: "نتحدث عن فكرتك وأهدافك ومتطلبات المشروع",
        process_step2_title: "تصميم وتخطيط",
        process_step2_desc: "أقدم لك نموذج أولي للموقع للموافقة عليه",
        process_step3_title: "تطوير و برمجة",
        process_step3_desc: "بناء الموقع بأحدث التقنيات مع مراجعات دورية",
        process_step4_title: "تسليم و دعم",
        process_step4_desc: "نطلق الموقع مع ضمان دعم فني لمدة أسبوع",

        // Pricing Section
        pricing_section_title: "الباقات و الأسعار",
        pricing_section_heading: "اختر الباقة المناسبة",
        pricing_section_subtitle: "أسعار تنافسية مع ضمان الجودة والاحترافية",
        pricing_landing_pages_type: "صفحات الهبوط",
        pricing_basic_landing_title: "الباقة الأساسية",
        pricing_basic_landing_feature_1: "صفحة واحدة",
        pricing_basic_landing_feature_2: "4 أقسام",
        pricing_basic_landing_feature_3: "تصميم متجاوب",
        pricing_basic_landing_feature_4: "نموذج اتصال",
        pricing_basic_landing_feature_5: "أيقونات وسائل التواصل الاجتماعي",
        pricing_professional_landing_title: "الباقة الاحترافية",
        pricing_professional_landing_feature_1: "صفحة واحدة",
        pricing_professional_landing_feature_2: "9 أقسام",
        pricing_professional_landing_feature_3: "تصميم مخصص",
        pricing_professional_landing_feature_4: "متجاوب مع كل الأجهزة",
        pricing_professional_landing_feature_5: "نموذج اتصال Form",
        pricing_professional_landing_feature_6: "أيقونات وسائل التواصل الاجتماعي",
        pricing_professional_landing_feature_7: "تحسين محركات البحث",
        pricing_premium_landing_title: "الباقة المتكاملة",
        pricing_premium_landing_feature_1: "3 صفحات",
        pricing_premium_landing_feature_2: "تصميم احترافي و مخصص",
        pricing_premium_landing_feature_3: "متجاوب مع كل الأجهزة",
        pricing_premium_landing_feature_4: "نموذج اتصال Form",
        pricing_premium_landing_feature_5: "أيقونات وسائل التواصل الاجتماعي",
        pricing_premium_landing_feature_6: "تحسين و تعديل قوي لمحركات البحث",
        pricing_premium_landing_feature_7: "دعم مجاني لمدة أسبوعين بعد التسليم",
        pricing_most_popular_badge: "الأكثر طلبا",
        pricing_order_button: "أطلب الان",
        pricing_full_websites_type: "مواقع كاملة",
        pricing_basic_full_title: "الباقة الأساسية",
        pricing_basic_full_feature_1: "5 صفحات رئيسية",
        pricing_basic_full_feature_2: "تصميم سلس",
        pricing_basic_full_feature_3: "متوافق مع جميع الأجهزة",
        pricing_basic_full_feature_4: "صفحة تواصل جاهزة",
        pricing_basic_full_feature_5: "أيقونات وسائل التواصل الاجتماعي مدمجة",
        pricing_professional_full_title: "الباقة الاحترافية",
        pricing_professional_full_feature_1: "8–10 صفحات كاملة",
        pricing_professional_full_feature_2: "تصميم مخصص يعكس هوية العلامة التجارية",
        pricing_professional_full_feature_3: "متجاوب مع كل الأجهزة",
        pricing_professional_full_feature_4: "نموذج اتصال متكامل",
        pricing_professional_full_feature_5: "تحسين أساسي لمحركات البحث",
        pricing_professional_full_feature_6: "أيقونات تواصل، معرض صور،فيديوهات",
        pricing_professional_full_feature_7: "تجربة مستخدم محسنة",
        pricing_premium_full_title: "الباقة المتكاملة",
        pricing_premium_full_feature_1: "12–15 صفحة أو أكثر حسب الطلب",
        pricing_premium_full_feature_2: "تصميم احترافي ومخصص بالكامل",
        pricing_premium_full_feature_3: "هوية بصرية كاملة",
        pricing_premium_full_feature_4: "تجربة مستخدم ممتازة على جميع الأجهزة",
        pricing_premium_full_feature_5: "نماذج متعددة، بوابات تواصل متعددة",
        pricing_premium_full_feature_6: "تحسين كامل لمحركات البحث + سرعة عالية للموقع",
        pricing_premium_full_feature_7: "دعم مجاني لمدة أسبوعين بعد التسليم",

        // Contact Section
        contact_section_title: "اتصل بي",
        contact_section_heading: "ابدأ مشروعك الان",
        contact_section_subtitle: "املأ النموذج وسأتواصل معك خلال 24 ساعة",
        contact_form_title: "لنصنع شيئاً رائعاً معاً",
        contact_form_subtitle: "أخبرني عن مشروعك وسأقدم لك أفضل الحلول المناسبة",
        contact_full_name: "الاسم الكامل *",
        contact_email: "البريد الاكتروني *",
        contact_project_details: "تفاصيل المشروع *",
        service_type_placeholder: "نوع الخدمة",
        service_type_full_website: "موقع كامل",
        service_type_landing_page: "صفحة هبوط",
        service_required_placeholder: "الخدمة المطلوبة",
        service_required_company: "موقع شركة",
        service_required_product_landing: "صفحة هبوط لمنتج",
        service_required_brand: "موقع لعلامتك التجارية",
        service_required_other: "أخرى",
        package_type_placeholder: "نوع الباقة",
        package_basic: "الباقة الأساسية",
        package_professional: "الباقة الاحترافية",
        package_premium: "الباقة المتكاملة",
        contact_submit_button: "إرسال الطلب",

        // FAQ Section
        faq_section_title: "الأسئلة الشائعة",
        faq_section_heading: "اجابات على أسئلتكم",
        faq_section_subtitle: "أجيب عن أكثر الأسئلة شيوعاً لمساعدتك في اتخاذ القرار",
        faq_q1: "كم يستغرق بناء موقع كامل؟",
        faq_a1: "يعتمد على حجم المشروع، المواقع البسيطة تستغرق أسبوعين، والمتاجر الإلكترونية 3-4 أسابيع.",
        faq_q2: "هل توفر خدمة استضافة ودومين؟",
        faq_a2: "لا, لكن اذا كنت مبتدأ و لا تعرف كيف تطلق موقعك فأنا أساعدك في اطلاقه",
        faq_q3: "ماذا بعد تسليم الموقع؟",
        faq_a3: "تقوم بشراء استضافة و تطلق عليها موقعك",
        faq_q4: "هل يمكن تعديل موقع قائم؟",
        faq_a4: "بالتأكيد، أقدم خدمات تطوير وتحسين للمواقع القائمة.",

        // Footer
        footer_logo: "WEB 7",
        footer_about_text: "مطور ويب محترف بخبرة 7 سنوات، أساعد الشركات والأفراد في بناء حضور رقمي قوي يحقق أهدافهم.",
        footer_quick_links_title: "روابط سريعة",
        footer_link_home: "الرئيسية",
        footer_link_services: "الخدمات",
        footer_link_portfolio: "أعمالي",
        footer_link_contact: "اتصل بي",
        footer_services_title: "الخدمات",
        footer_service_company: "مواقع شركات",
        footer_service_landing_pages: "صفحات هبوط",
        footer_service_brand: "مواقع للعلامات التجارية",
        footer_service_product_landing: "صفحات هبوط للمنتجات",
        footer_copyright: "جميع الحقوق محفوظة"
    },
    fr: {
        // Header
        web7_logo_text: "WEB 7",
        nav_home: "Accueil",
        nav_services: "Services",
        nav_portfolio: "Portfolio",
        nav_process: "Processus",
        nav_pricing: "Forfaits",
        nav_contact: "Contact",
        lang_arabic: "Arabe",
        lang_english: "EN",
        lang_french: "FR",

        // Hero Section
        hero_badge: "Développeur Web Certifié",
        hero_title: "Transformez vos idées en sites et pages web professionnels",
        hero_subtitle: "Je construis des sites et des pages web qui contribuent à la croissance de votre entreprise et à l'augmentation de vos bénéfices, avec des designs modernes et une expérience utilisateur fluide.",
        stat_completed_projects_count: "+36",
        stat_completed_projects: "Projets Réalisés",
        stat_happy_clients_count: "+36",
        stat_happy_clients: "Clients Satisfaits",
        stat_improvements_count: "+15",
        stat_improvements: "Modifications & Améliorations",
        cta_start_project: "Commencez Votre Projet",
        cta_view_work: "Voir Mon Travail",

        // Trust Section
        trust_custom_design_title: "Design Personnalisé",
        trust_custom_design_desc: "100% à vous",
        trust_support_title: "Support 24/7",
        trust_support_desc: "Toute la semaine",
        trust_fast_delivery_title: "Livraison Rapide",
        trust_fast_delivery_desc: "Sous 7-14 jours",
        trust_clean_code_title: "Code Propre et Sécurisé",
        trust_clean_code_desc: "Avec les dernières technologies",

        // Services Section
        services_section_title: "Services",
        services_section_heading: "Qu'est-ce que je vous propose ?",
        services_section_subtitle: "Des solutions intégrées adaptées à vos besoins pour vous aider à atteindre vos objectifs numériques",
        service_company_websites_title: "Sites d'Entreprises",
        service_company_websites_desc: "Des sites professionnels qui reflètent l'identité de votre entreprise et présentent vos services de manière distinctive",
        service_feature_custom_design: "Design Personnalisé",
        service_feature_responsive: "Responsive sur tous les appareils",
        service_feature_seo: "Optimisation SEO",
        service_landing_pages_title: "Pages d'Atterrissage",
        service_landing_pages_desc: "Des pages marketing professionnelles qui augmentent les taux de conversion",
        service_feature_attractive_design: "Design Attrayant",
        service_feature_high_speed: "Haute Vitesse",
        service_feature_responsive_all: "Responsive sur tous les appareils",
        service_product_landing_pages_title: "Pages d'Atterrissage pour Produits",
        service_product_landing_pages_desc: "Des pages d'atterrissage personnalisées pour vos produits conçues pour augmenter les ventes et convertir les visiteurs en clients, avec une concentration totale sur la persuasion et la facilité d'achat.",
        service_feature_sales_oriented: "Design orienté vente",
        service_feature_high_load_speed: "Vitesse de chargement élevée pour réduire le taux de rebond",
        service_feature_sales_optimized: "Optimisé pour augmenter les ventes et obtenir des résultats réels",
        service_brand_websites_title: "Sites Professionnels pour Marques et Services",
        service_brand_websites_desc: "Des sites professionnels qui reflètent la force de votre marque, adaptés aux restaurants, hôtels, cliniques et entreprises, avec une expérience utilisateur distinctive qui construit la confiance et attire les clients.",
        service_feature_brand_identity: "Design qui reflète l'identité de la marque",
        service_feature_interactive_services: "Réservation et services interactifs (Restaurants / Cliniques / Hôtels)",
        service_feature_search_visibility: "Visibilité améliorée sur les moteurs de recherche",
        service_figma_conversion_title: "Convertir un Design Figma en Site Web Réel",
        service_figma_conversion_desc: "Je convertis votre design Figma en un site web professionnel, rapide et responsive, fonctionnant sur tous les appareils avec un code propre et organisé.",
        service_feature_accurate_conversion: "Conversion précise du design tel que dans Figma",
        service_feature_clean_code: "Code propre et facile à modifier à l'avenir",
        service_feature_responsive_mobile_desktop: "Site responsive sur mobile et ordinateur",
        service_seo_title: "Optimisation SEO",
        service_seo_desc: "Résultats avancés dans les moteurs de recherche pour augmenter les visiteurs",
        service_feature_keyword_analysis: "Analyse des Mots-clés",
        service_feature_speed_optimization: "Optimisation de la Vitesse",
        service_feature_clean_urls: "URLs Propres",

        // Portfolio Section
        portfolio_section_title: "Portfolio",
        portfolio_section_heading: "Projets Précédents",
        portfolio_section_subtitle: "Une collection de projets réalisés pour des clients dans divers domaines",
        portfolio_real_estate_title: "Site Web d'Agence Immobilière",
        portfolio_dentist_title: "Page d'Atterrissage pour Cabinet Dentaire",
        portfolio_hotel_title: "Site Web d'Hôtel",
        trestt: "Vendez votre bien rapidement et professionnellement avec un site qui le met en valeur",
        trrestp: "Un site web spécialement conçu pour les propriétaires immobiliers afin de présenter leurs biens de manière attrayante, afficher clairement les prix et les caractéristiques, attirer des clients et augmenter les opportunités de vente.",
        trdtt: "Attirez plus de patients dentaires avec une page de réservation facile et professionnelle",
        trdd: "Une page de destination spécialement conçue pour votre clinique, présentant vos services de manière professionnelle et permettant aux patients de prendre rendez-vous facilement, augmentant les réservations et simplifiant votre gestion.",
        trhtt: "Augmentez les réservations de votre hôtel avec un site rapide et professionnel qui attire les clients",
        trhtd: "Un site conçu pour les hôtels afin d’augmenter les réservations, rapide, responsive sur tous les appareils, présentant vos services de manière professionnelle avec un système de réservation permettant aux clients de réserver instantanément.",


        // Why Us Section
        why_us_section_title: "Pourquoi WEB 7 ?",
        why_us_section_heading: "Raisons de me Choisir",
        why_us_section_subtitle: "Expérience, qualité et professionnalisme dans chaque projet",
        why_real_results_title: "Résultats Concrets",
        why_real_results_desc: "Des sites conçus pour augmenter les clients et les ventes",
        why_performance_title: "Haute Performance & Rapidité",
        why_performance_desc: "Des sites rapides optimisés pour une expérience utilisateur parfaite",
        why_on_time_title: "Livraison Ponctuelle",
        why_on_time_desc: "Toujours respect des délais",
        why_free_support_title: "Support Gratuit",
        why_free_support_desc: "Une semaine après la livraison",

        // Testimonials
        testimonial_1_text: "J'ai travaillé avec plusieurs développeurs, mais WEB 7 était le meilleur dans tous les sens. Il a compris mes besoins avec précision et a exécuté le projet avec un grand professionnalisme, a respecté les délais et a été en communication constante avec moi tout au long de la période de travail.",
        testimonial_1_name: "Ahmed Ali",
        testimonial_1_role: "Page d'Atterrissage Produit Réussie",
        testimonial_2_text: "Honnêtement, je ne m'attendais pas à ce que le site fasse une telle différence. Je voulais juste une présence en ligne. Mais après que Mohamed ait travaillé dessus, j'ai remarqué que plus de gens visitaient, s'informaient et venaient même au restaurant. Une énorme différence par rapport à avant. J'ai vraiment senti que mon service atteignait les gens.",
        testimonial_2_name: "Abdulrahman",
        testimonial_2_role: "Site de Restaurant",
        testimonial_3_text: "Honnêtement, je ne m'attendais pas à ce qu'une simple page fasse une telle différence. Je pensais que c'était juste une chose secondaire. Mais après avoir travaillé avec WEB 7, j'ai remarqué que plus de gens me contactaient et prenaient rendez-vous, et les demandes ont considérablement augmenté. Une énorme différence par rapport à avant.",
        testimonial_3_name: "Khaled",
        testimonial_3_role: "Page d'Atterrissage pour Cabinet Dentaire",
        testimonial_4_text: "J'ai travaillé avec plusieurs développeurs, mais WEB 7 était le meilleur dans tous les sens. Il a compris mes besoins avec précision et a exécuté le projet avec un grand professionnalisme, a respecté les délais et a été en communication constante avec moi tout au long de la période de travail.",
        testimonial_4_name: "Ahmed Ali",
        testimonial_4_role: "Page d'Atterrissage Produit Réussie",
        testimonial_5_text: "Honnêtement, je ne m'attendais pas à ce que le site fasse une telle différence. Je voulais juste une présence en ligne. Mais après que Mohamed ait travaillé dessus, j'ai remarqué que plus de gens visitaient, s'informaient et venaient même au restaurant. Une énorme différence par rapport à avant. J'ai vraiment senti que mon service atteignait les gens.",
        testimonial_5_name: "Abdulrahman",
        testimonial_5_role: "Site de Restaurant",
        testimonial_6_text: "Honnêtement, je ne m'attendais pas à ce qu'une simple page fasse une telle différence. Je pensais que c'était juste une chose secondaire. Mais après avoir travaillé avec WEB 7, j'ai remarqué que plus de gens me contactaient et prenaient rendez-vous, et les demandes ont considérablement augmenté. Une énorme différence par rapport à avant.",
        testimonial_6_name: "Khaled",
        testimonial_6_role: "Page d'Atterrissage pour Cabinet Dentaire",

        // Process Section
        process_section_title: "Processus de Travail",
        process_section_heading: "Comment je travaille avec vous ?",
        process_section_subtitle: "Des étapes claires et organisées pour garantir le meilleur résultat",
        process_step1_title: "Consultation Gratuite",
        process_step1_desc: "Nous parlons de votre idée, vos objectifs et les exigences du projet",
        process_step2_title: "Design & Planification",
        process_step2_desc: "Je vous fournis un prototype du site pour approbation",
        process_step3_title: "Développement & Programmation",
        process_step3_desc: "Construction du site avec les dernières technologies avec des revues périodiques",
        process_step4_title: "Livraison & Support",
        process_step4_desc: "Nous lançons le site avec un support technique garanti pendant une semaine",

        // Pricing Section
        pricing_section_title: "Forfaits & Prix",
        pricing_section_heading: "Choisissez le Forfait Adapté",
        pricing_section_subtitle: "Des prix compétitifs avec une qualité et un professionnalisme garantis",
        pricing_landing_pages_type: "des Pages d'Atterrissage",
        pricing_basic_landing_title: "Forfait de Base",
        pricing_basic_landing_feature_1: "Page Unique",
        pricing_basic_landing_feature_2: "4 Sections",
        pricing_basic_landing_feature_3: "Design Responsive",
        pricing_basic_landing_feature_4: "Formulaire de Contact",
        pricing_basic_landing_feature_5: "Icônes des Réseaux Sociaux",
        pricing_professional_landing_title: "Forfait Professionnel",
        pricing_professional_landing_feature_1: "Page Unique",
        pricing_professional_landing_feature_2: "9 Sections",
        pricing_professional_landing_feature_3: "Design Personnalisé",
        pricing_professional_landing_feature_4: "Responsive sur tous les appareils",
        pricing_professional_landing_feature_5: "Formulaire de Contact",
        pricing_professional_landing_feature_6: "Icônes des Réseaux Sociaux",
        pricing_professional_landing_feature_7: "Optimisation SEO",
        pricing_premium_landing_title: "Forfait Premium",
        pricing_premium_landing_feature_1: "3 Pages",
        pricing_premium_landing_feature_2: "Design Professionnel & Personnalisé",
        pricing_premium_landing_feature_3: "Responsive sur tous les appareils",
        pricing_premium_landing_feature_4: "Formulaire de Contact",
        pricing_premium_landing_feature_5: "Icônes des Réseaux Sociaux",
        pricing_premium_landing_feature_6: "Optimisation SEO Avancée",
        pricing_premium_landing_feature_7: "Support gratuit pendant deux semaines après la livraison",
        pricing_most_popular_badge: "Le Plus Populaire",
        pricing_order_button: "Commander",
        pricing_full_websites_type: "des Sites Complets",
        pricing_basic_full_title: "Forfait de Base",
        pricing_basic_full_feature_1: "5 Pages Principales",
        pricing_basic_full_feature_2: "Design Épuré",
        pricing_basic_full_feature_3: "Compatible avec tous les appareils",
        pricing_basic_full_feature_4: "Page de Contact Prête",
        pricing_basic_full_feature_5: "Icônes des Réseaux Sociaux Intégrées",
        pricing_professional_full_title: "Forfait Professionnel",
        pricing_professional_full_feature_1: "8–10 Pages Complètes",
        pricing_professional_full_feature_2: "Design personnalisé reflétant l'identité de la marque",
        pricing_professional_full_feature_3: "Responsive sur tous les appareils",
        pricing_professional_full_feature_4: "Formulaire de Contact Intégré",
        pricing_professional_full_feature_5: "Optimisation SEO de Base",
        pricing_professional_full_feature_6: "Icônes sociales, galerie d'images, vidéos",
        pricing_professional_full_feature_7: "Expérience Utilisateur Améliorée",
        pricing_premium_full_title: "Forfait Premium",
        pricing_premium_full_feature_1: "12–15 pages ou plus selon la demande",
        pricing_premium_full_feature_2: "Design Professionnel et Entièrement Personnalisé",
        pricing_premium_full_feature_3: "Identité Visuelle Complète",
        pricing_premium_full_feature_4: "Excellente expérience utilisateur sur tous les appareils",
        pricing_premium_full_feature_5: "Formulaires multiples, portails de communication multiples",
        pricing_premium_full_feature_6: "Optimisation SEO Complète + Haute Vitesse du Site",
        pricing_premium_full_feature_7: "Support gratuit pendant deux semaines après la livraison",

        // Contact Section
        contact_section_title: "Contactez-moi",
        contact_section_heading: "Commencez Votre Projet Maintenant",
        contact_section_subtitle: "Remplissez le formulaire et je vous contacterai dans les 24 heures",
        contact_form_title: "Créons Quelque Chose d'Extraordinaire Ensemble",
        contact_form_subtitle: "Parlez-moi de votre projet et je vous fournirai les meilleures solutions",
        contact_full_name: "Nom Complet *",
        contact_email: "Email *",
        contact_project_details: "Détails du Projet *",
        service_type_placeholder: "Type de Service",
        service_type_full_website: "Site Complet",
        service_type_landing_page: "Page d'Atterrissage",
        service_required_placeholder: "Service Demandé",
        service_required_company: "Site d'Entreprise",
        service_required_product_landing: "Page d'Atterrissage pour Produit",
        service_required_brand: "Site pour Votre Marque",
        service_required_other: "Autre",
        package_type_placeholder: "Type de Forfait",
        package_basic: "Forfait de Base",
        package_professional: "Forfait Professionnel",
        package_premium: "Forfait Premium",
        contact_submit_button: "Envoyer la Demande",

        // FAQ Section
        faq_section_title: "Questions Fréquentes",
        faq_section_heading: "Réponses à Vos Questions",
        faq_section_subtitle: "Je réponds aux questions les plus courantes pour vous aider à prendre une décision",
        faq_q1: "Combien de temps faut-il pour construire un site complet ?",
        faq_a1: "Cela dépend de la taille du projet. Les sites simples prennent deux semaines, les sites e-commerce 3-4 semaines.",
        faq_q2: "Fournissez-vous des services d'hébergement et de domaine ?",
        faq_a2: "Non, mais si vous êtes débutant et que vous ne savez pas comment lancer votre site, je vous aide à le lancer.",
        faq_q3: "Que se passe-t-il après la livraison du site ?",
        faq_a3: "Vous achetez un hébergement et vous y lancez votre site.",
        faq_q4: "Pouvez-vous modifier un site existant ?",
        faq_a4: "Absolument, je fournis des services de développement et d'amélioration pour les sites existants.",

        // Footer
        footer_logo: "WEB 7",
        footer_about_text: "Développeur web professionnel avec 7 ans d'expérience. J'aide les entreprises et les particuliers à construire une présence numérique solide qui atteint leurs objectifs.",
        footer_quick_links_title: "Liens Rapides",
        footer_link_home: "Accueil",
        footer_link_services: "Services",
        footer_link_portfolio: "Portfolio",
        footer_link_contact: "Contact",
        footer_services_title: "Services",
        footer_service_company: "Sites d'Entreprises",
        footer_service_landing_pages: "Pages d'Atterrissage",
        footer_service_brand: "Sites de Marques",
        footer_service_product_landing: "Pages d'Atterrissage Produits",
        footer_copyright: "Tous Droits Réservés"
    }
};

// دالة الترجمة
let iconeContact = document.getElementById("iconeContact");

function translatePage(lang,btn){
    let btns = document.querySelectorAll(".btnLang");
    btns.forEach(button =>{
        button.classList.remove("active");
    });
    btn.classList.add("active");
    let allElements = document.querySelectorAll("[data-tr]")
    allElements.forEach(element =>{
        const key = element.getAttribute("data-tr")
        element.textContent = translations[lang][key]

    }) ;
    
    let placeholders = document.querySelectorAll("[data-tr-placeholder]");
    placeholders.forEach(element => {
        const key = element.getAttribute('data-tr-placeholder');
        const translation = translations[lang][key];
        if (translation !== undefined) {
            element.placeholder = translation;
        }
    });
    let ENStyle=document.getElementById("ENStyle");
    let HeroContentGradient = document.getElementById("HeroContentGradient");
    if(lang === 'en' || lang === 'fr'){
        document.documentElement.setAttribute('dir', 'ltr');
        document.documentElement.setAttribute('lang', lang);
        iconeContact.style.display="none";
        ENStyle.disabled=false;
        
        
    }else if(lang === 'ar'){
        document.documentElement.setAttribute('dir', 'rtl');
        document.documentElement.setAttribute('lang', lang);
        iconeContact.style.right = "50px";
        ENStyle.disabled=true;
        HeroContentGradient.innerHTML = `<h1 data-tr="hero_title" id="HeroContentGradient">أحول أفكارك الى <span>مواقع وصفحات</span> احترافية</h1>`;
    }
    if(lang === 'en'){
        HeroContentGradient.innerHTML = `<h1 data-tr="hero_title" id="HeroContentGradient">Turn Your Ideas into <span>Professional Websites </span>& Pages</h1>`;
    }else if(lang === 'fr'){
        HeroContentGradient.innerHTML = `<h1 data-tr="hero_title" id="HeroContentGradient">Transformez vos idées en <span>sites et pages web </span>professionnels</h1>`;

    }

    
    
} 